-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Create a table for public profiles linked to auth.users
create table public.users (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  display_name text,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for users
alter table public.users enable row level security;

create policy "Public profiles are viewable by everyone."
  on public.users for select
  using ( true );

create policy "Users can insert their own profile."
  on public.users for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on public.users for update
  using ( auth.uid() = id );

-- Create a table for meetings (IDs are text like '123-456-789' generated by App)
create table public.meetings (
  id text primary key, -- Changed from uuid to text to match App.tsx format
  host_id uuid references public.users(id) not null,
  title text not null,
  scheduled_at timestamp with time zone,
  status text check (status in ('scheduled', 'active', 'ended')) default 'scheduled',
  passcode text,
  config jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for meetings
alter table public.meetings enable row level security;

create policy "Meetings are viewable by everyone."
  on public.meetings for select
  using ( true );

create policy "Host can update their own meetings."
  on public.meetings for update
  using ( auth.uid() = host_id );

create policy "Host can insert meetings."
  on public.meetings for insert
  with check ( auth.uid() = host_id );

-- Create a table for participants
create table public.participants (
  id uuid default uuid_generate_v4() primary key,
  meeting_id text references public.meetings(id) on delete cascade not null, -- Changed to text
  user_id uuid references public.users(id), -- Nullable for guests
  name text not null,
  role text check (role in ('host', 'guest', 'ai')) default 'guest',
  status text check (status in ('waiting', 'approved', 'active', 'left')) default 'waiting',
  joined_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for participants
alter table public.participants enable row level security;

create policy "Participants are viewable by everyone in the meeting."
  on public.participants for select
  using ( true );

create policy "Participants can insert themselves."
  on public.participants for insert
  with check ( true ); 

create policy "Participants can update themselves."
  on public.participants for update
  using ( true );

-- Create a table for messages
create table public.messages (
  id uuid default uuid_generate_v4() primary key,
  meeting_id text references public.meetings(id) on delete cascade not null, -- Changed to text
  sender_id uuid references public.participants(id),
  content text,
  type text check (type in ('text', 'system', 'ai')) default 'text',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for messages
alter table public.messages enable row level security;

create policy "Messages are viewable by everyone in the meeting."
  on public.messages for select
  using ( true );

create policy "Participants can insert messages."
  on public.messages for insert
  with check ( true );

-- Create a table for AI generations
create table public.ai_generations (
  id uuid default uuid_generate_v4() primary key,
  meeting_id text references public.meetings(id) on delete cascade not null, -- Changed to text
  tool_type text not null,
  input_prompt text,
  output_content jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for ai_generations
alter table public.ai_generations enable row level security;

create policy "AI generations are viewable by everyone in the meeting."
  on public.ai_generations for select
  using ( true );

create policy "Participants can insert AI generations."
  on public.ai_generations for insert
  with check ( true );

-- Create a table for Transcriptions (Required by App.tsx)
create table public.transcriptions (
  id uuid default uuid_generate_v4() primary key,
  session_id text not null, -- Matches meeting_id (text)
  user_id text, -- Supports 'guest-123' string IDs
  text text,
  timestamp timestamp with time zone default now()
);

-- Enable RLS for transcriptions
alter table public.transcriptions enable row level security;

create policy "Everyone can view transcriptions"
  on public.transcriptions for select
  using ( true );

create policy "Everyone can insert transcriptions"
  on public.transcriptions for insert
  with check ( true );


-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (id, email, display_name, avatar_url)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call handle_new_user on auth.users insert
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Add translation preferences to users table
alter table public.users add column if not exists translation_preferences jsonb default '{}'::jsonb;

-- Create translation cache table for performance optimization
create table if not exists public.translation_cache (
  id uuid default uuid_generate_v4() primary key,
  source_text text not null,
  source_lang text not null,
  target_lang text not null,
  translated_text text not null,
  quality_score float,
  context_hash text, -- Hash of conversation context for context-aware caching
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  expires_at timestamp with time zone default timezone('utc'::text, now() + interval '7 days') not null
);

-- Create index for fast translation lookups
create index if not exists idx_translation_cache_lookup 
  on public.translation_cache(source_text, source_lang, target_lang, context_hash);

-- Create index for cache cleanup (expired entries)
create index if not exists idx_translation_cache_expires 
  on public.translation_cache(expires_at);

-- Enable RLS for translation_cache
alter table public.translation_cache enable row level security;

create policy "Translation cache is readable by everyone."
  on public.translation_cache for select
  using ( true );

create policy "Anyone can insert translations."
  on public.translation_cache for insert
  with check ( true );

-- ============================================================================
-- LIVE CAPTIONS SYSTEM (Advanced - defined just in case, but App uses transcriptions table)
-- ============================================================================

-- caption_segments: Stores final STT captions for each meeting
create table if not exists public.caption_segments (
  id uuid default uuid_generate_v4() primary key,
  meeting_id text references public.meetings(id) on delete cascade not null, -- Changed to text
  speaker_peer_id text not null,
  speaker_name text not null,
  source_lang text not null default 'en',
  text_final text not null,
  stt_meta jsonb default '{}'::jsonb, -- Metadata: confidence, timings, etc.
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists idx_caption_segments_meeting 
  on public.caption_segments(meeting_id, created_at desc);

create index if not exists idx_caption_segments_speaker
  on public.caption_segments(meeting_id, speaker_peer_id, created_at desc);

-- Enable RLS for caption_segments
alter table public.caption_segments enable row level security;

create policy "Meeting participants can read captions"
  on public.caption_segments for select
  using ( true );

create policy "Meeting participants can insert captions"
  on public.caption_segments for insert
  with check ( true );

-- caption_translations: Translated versions of captions
create table if not exists public.caption_translations (
  id uuid default uuid_generate_v4() primary key,
  meeting_id text references public.meetings(id) on delete cascade not null, -- Changed to text
  segment_id uuid references public.caption_segments(id) on delete cascade not null,
  target_lang text not null,
  translated_text text not null,
  tts_style_prompt text,
  quality_score float,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(segment_id, target_lang)
);

create index if not exists idx_caption_translations_lookup 
  on public.caption_translations(meeting_id, target_lang, created_at desc);

create index if not exists idx_caption_translations_segment
  on public.caption_translations(segment_id);

-- Enable RLS for caption_translations
alter table public.caption_translations enable row level security;

create policy "Meeting participants can read translations"
  on public.caption_translations for select
  using ( true );

create policy "Anyone can insert translations"
  on public.caption_translations for insert
  with check ( true );

-- meeting_language_targets: Track active target languages per meeting/user
create table if not exists public.meeting_language_targets (
  id uuid default uuid_generate_v4() primary key,
  meeting_id text references public.meetings(id) on delete cascade not null, -- Changed to text
  user_id uuid references public.users(id) on delete cascade,
  peer_id text, -- For guest users without auth
  target_lang text not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(meeting_id, user_id),
  unique(meeting_id, peer_id)
);

create index if not exists idx_meeting_language_targets 
  on public.meeting_language_targets(meeting_id);

-- Enable RLS for meeting_language_targets
alter table public.meeting_language_targets enable row level security;

create policy "Meeting participants can read language targets"
  on public.meeting_language_targets for select
  using ( true );

create policy "Users can manage their own language target"
  on public.meeting_language_targets for insert
  with check ( true );

create policy "Users can update their own language target"
  on public.meeting_language_targets for update
  using ( true );

create policy "Users can delete their own language target"
  on public.meeting_language_targets for delete
  using ( true );
